In [1]:
import pandas as pd

df = pd.read_csv('data/FireStatLA/UCLA Heat Days - Daily Incident Summary.csv')
df.head()

  Incident Date  FSDistrict                IncidentCategory  IncidentCount
0    01/01/2018           1                      AUTOMOBILE              1
1    01/01/2018           1                           BURNS              1
2    01/01/2018           1  CHEST DISCOMFORT/HEART PROBLEM              1
3    01/01/2018           1                        DIABETIC              1
4    01/01/2018           1                            FALL              2

In [2]:
df.tail()

,Incident Date,FSDistrict,IncidentCategory,IncidentCount
1475661,12/31/2022,109,TRAFFIC,1
1475662,12/31/2022,112,ASSAULT,1
1475663,12/31/2022,112,CHEST DISCOMFORT/HEART PROBLEM,1
1475664,12/31/2022,112,FALL,3
1475665,12/31/2022,112,O.D./POISONING,1

In [3]:
# i deleted the column FSDistrict in the beggining just to not be displayed in the result , then i applied the groupby function
# on the columns date and incident category to show for each day which accident category occured

res = df.drop('FSDistrict', axis=1).groupby(["Incident Date",'IncidentCategory']).sum()

In [4]:
res.head()

                                    IncidentCount
Incident Date IncidentCategory
01/01/2018    ABDOMINAL                        47
              ALLERGY/ENVENOMATION              8
              ANIMAL BITE                       2
              ASSAULT                          86
              AUTOMATIC ALARM                  48

In [5]:
# i did the same here i deleted the column incidentcount to show only the date and incident category
res.drop("IncidentCount", axis=1).head(50)

Empty DataFrame
Columns: []
Index: [(01/01/2018, ABDOMINAL), (01/01/2018, ALLERGY/ENVENOMATION), (01/01/2018, ANIMAL BITE), (01/01/2018, ASSAULT), (01/01/2018, AUTOMATIC ALARM), (01/01/2018, AUTOMOBILE), (01/01/2018, BELLS RINGING), (01/01/2018, BLEEDING (NON-TRAUMATIC)), (01/01/2018, BREATHING DIFFICULTY), (01/01/2018, BRUSH), (01/01/2018, BURNS), (01/01/2018, CARDIAC/RESP. ARREST), (01/01/2018, CHEMICAL), (01/01/2018, CHEST DISCOMFORT/HEART PROBLEM), (01/01/2018, CHOKING), (01/01/2018, DIABETIC), (01/01/2018, ELECTRICAL), (01/01/2018, ELEVATOR), (01/01/2018, FALL), (01/01/2018, GRASS), (01/01/2018, HEADACHE), (01/01/2018, INJURY), (01/01/2018, INTERFACILITY TRANSFER), (01/01/2018, LOCKOUT), (01/01/2018, O.D./POISONING), (01/01/2018, OB/GYN), (01/01/2018, OVEN), (01/01/2018, PEDIATRICS), (01/01/2018, POLE), (01/01/2018, PSYCH/SA/EMOTIONAL), (01/01/2018, RUBBISH), (01/01/2018, SEIZURE), (01/01/2018, SHOOTING), (01/01/2018, SICK), (01/01/2018, SMOKE), (01/01/2018, SMOKE DETECTOR), (01/01/2018, STABBING), (01/01/2018, STROKE), (01/01/2018, STRUCTURE), (01/01/2018, STRUCTURE-AA), (01/01/2018, TOXIC), (01/01/2018, TRAFFIC), (01/01/2018, TREE), (01/01/2018, UNCONSCIOUS/FAINTING), (01/01/2018, UNKNOWN PROBLEM), (01/01/2018, VEHICULAR), (01/01/2018, WATER-RELATED), (01/01/2019, ABDOMINAL), (01/01/2019, ALLERGY/ENVENOMATION), (01/01/2019, ANIMAL BITE)]

In [6]:
# 2- groupby on each unique day by Fire district
res2 = df.groupby(["Incident Date","FSDistrict",'IncidentCategory']).sum()
res2.head(30)

                                                         IncidentCount
Incident Date FSDistrict IncidentCategory
01/01/2018    1          AUTOMOBILE                                  1
                         BURNS                                       1
                         CHEST DISCOMFORT/HEART PROBLEM              1
                         DIABETIC                                    1
                         FALL                                        2
                         INTERFACILITY TRANSFER                      1
                         O.D./POISONING                              1
                         RUBBISH                                     1
                         TRAFFIC                                     1
                         TREE                                        1
                         UNCONSCIOUS/FAINTING                        1
                         UNKNOWN PROBLEM                             1
              2          CHEST DISCOMFORT/HEART PROBLEM              1
                         DIABETIC                                    1
                         FALL                                        1
                         PEDIATRICS                                  1
                         RUBBISH                                     2
                         SICK                                        3
                         STRUCTURE                                   1
                         UNKNOWN PROBLEM                             1
                         WATER-RELATED                               1
              3          ABDOMINAL                                   1
                         ASSAULT                                     2
                         AUTOMATIC ALARM                             3
                         CHEMICAL                                    1
                         FALL                                        1
                         O.D./POISONING                              1
                         RUBBISH                                     1
                         SEIZURE                                     1
                         STABBING                                    1